name: Sabreen CI

# when to run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# what jobs to run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # set up Java
      - name: JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # test with maven
      - name: Maven
        run: mvn clean test
