name: Java CI with Maven

on:
  push:
    branches:
      - master  #anyone pushes to 'Master' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adoptopenjdk'  # You can also use 'temurin' or 'zulu'
        java-version: '11'
        java-package: jdk
        architecture: x64
        check-latest: false

    - name: Build with Maven
      run: mvn clean test  #build & test commands
