name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK 11 (specify distribution as 'adoptopenjdk')
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'adoptopenjdk'  # This specifies the distribution
        cache: maven # Optional, caches Maven dependencies for faster builds

    # Build with Maven
    - name: Build with Maven
      run: mvn clean install

    # Run tests with Maven
    - name: Run tests with Maven
      run: mvn test
